workflows:
  ios-ci:
    name: iOS CI
    # optional: max_build_duration, instance_type, etc.
    environment:
      flutter: stable
      xcode: latest
      # cocoapods: default    # ← uncomment if you want CodeMagic to cache pods
    scripts:
      - name: Get Dart packages
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS (unsigned)
        script: flutter build ios --no-codesign
