workflows:
  ios-android-ci:
    name: iOS and Android CI
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Dart packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --no-repo-update
          cd ..

      - name: Decode and Install iOS Certificate and Profile
        script: |
          # Decode and save the iOS certificate
          echo $IOS_CERTIFICATE_BASE64 | base64 --decode > /tmp/akonnct.p12
          security import /tmp/akonnct.p12 -P "$IOS_CERTIFICATE_PASSWORD" -A

          # Create the Provisioning Profile directory
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles

          # Decode and save the Provisioning Profile
          echo $IOS_PROVISIONING_PROFILE_BASE64 | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/akonnct.mobileprovision

      - name: Build iOS (Signed)
        script: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -archivePath build/ios/Runner.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath build/ios/Runner.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ios/ipa \
            -allowProvisioningUpdates
      
      - name: Zip iOS .app for download
        script: |
          mkdir -p artifacts
          cp -r build/ios/ipa/*.ipa artifacts/Runner.ipa
          cd artifacts
          zip -r Runner.app.zip Runner.ipa

      - name: Build Android AAB (Signed)
        script: flutter build appbundle --release --build-name=1.0.0 --build-number=1

    artifacts:
      - artifacts/Runner.app.zip
      - artifacts/Runner.ipa
      - build/app/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - your_email@example.com
        notify_on_build_success: true
        notify_on_build_failure: true
