name: connect_app
description: "A Flutter app with Firebase integration."
publish_to: none

version: 1.0.0+10

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^7.0.1
  agora_rtc_engine: ^6.1.2
  permission_handler: ^12.0.0+1
  provider: ^6.1.2

  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  firebase_core: ^3.5.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^19.2.1
  firebase_app_check: ^0.3.2+6
  cloud_functions: ^5.3.4

  in_app_purchase: ^3.2.1
  http: ^1.0.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  flutter_stripe: ^11.4.0

  crypto: ^3.0.3

  shimmer: ^3.0.0

  photo_view: ^0.15.0
  video_player: ^2.9.1
  chewie: ^1.7.5
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.3
  firebase_dynamic_links: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # ✅ Downgraded to support Dart 3.6.0
  mockito: ^5.4.5       # ✅ Compatible with Dart 3.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_profile.png
