name: connect_app
description: "A Flutter app with Firebase integration."

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # State Management
  provider: ^6.1.2

  # Firebase Integration
  firebase_core: ^3.9.0
  firebase_auth: ^5.4.0 # Latest version
  cloud_firestore: ^5.6.1 # Latest version
  firebase_storage: ^12.4.0 # Latest version

  # HTTP Requests
  http: ^1.0.0

  # Flutter-specific packages
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

  # Image picking
  image_picker: ^1.1.2 # Latest version

  # UUID generation
  uuid: ^4.5.1 # Latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Include assets (default profile picture)
  assets:
    - assets/default_profile.png
