// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT6rrIVgwsCsG_RlGffmbklMv2S-K9WWc',
    appId: '1:33757728932:web:dc17294a56ba19819a1631',
    messagingSenderId: '33757728932',
    projectId: 'connectapp-278b4',
    authDomain: 'connectapp-278b4.firebaseapp.com',
    storageBucket: 'connectapp-278b4.firebasestorage.app',
    measurementId: 'G-HS93X1LC2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJGwDmjDJ6FsshG8BwBjjoYatmXSdxjaI',
    appId: '1:33757728932:android:73e90795594218b79a1631',
    messagingSenderId: '33757728932',
    projectId: 'connectapp-278b4',
    storageBucket: 'connectapp-278b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2OAMOmE3sPh60XthLCh7kZW6phZ3l8AI',
    appId: '1:33757728932:ios:d2344cfb0f8f08f19a1631',
    messagingSenderId: '33757728932',
    projectId: 'connectapp-278b4',
    storageBucket: 'connectapp-278b4.firebasestorage.app',
    iosBundleId: 'com.example.connectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2OAMOmE3sPh60XthLCh7kZW6phZ3l8AI',
    appId: '1:33757728932:ios:d2344cfb0f8f08f19a1631',
    messagingSenderId: '33757728932',
    projectId: 'connectapp-278b4',
    storageBucket: 'connectapp-278b4.firebasestorage.app',
    iosBundleId: 'com.example.connectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT6rrIVgwsCsG_RlGffmbklMv2S-K9WWc',
    appId: '1:33757728932:web:ec2439d18af0adbf9a1631',
    messagingSenderId: '33757728932',
    projectId: 'connectapp-278b4',
    authDomain: 'connectapp-278b4.firebaseapp.com',
    storageBucket: 'connectapp-278b4.firebasestorage.app',
    measurementId: 'G-0QVPFDWBFB',
  );

}